"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

SECRET_KEY = env("SECRET_KEY")  # ✅
DEBUG = env("DEBUG")
ALLOWED_HOSTS = []
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "todo",
    "rest_framework",
    "accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# REST_FRAMEWORK = {
#     "DEFAULT_RENDERER_CLASSES": [
#         "rest_framework.renderers.JSONRenderer",
#     ],
# }
# REST_FRAMEWORK = {
#     # 기본권한 설정: 누구나 API에 접근 가능(개발시 사용)
#     "DEFAULT_PERMISSION_CLASSES": [
#         "rest_framework.permissions.AllowAny",
#     ],
#     # 기본 페이지네이션 설정
#     "DEFAULT_PAGINATION_CLASS": "todo.pagination.CustomPageNumberPagination",
#     "PAGE_SIZE": 3,
#     # API응답형식
#     "DEFAULT_RENDERER_CLASSES": [
#         "rest_framework.renderers.JSONRenderer",
#         "rest_framework.renderers.BrowsableAPIRenderer",
#     ],
# }

# Django REST Framework 전역 설정
REST_FRAMEWORK = {
    # 인증 방식 설정
    # API 요청을 보낸 사용자가 누구인지 확인하는 방법
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # 세션 인증 (Django 로그인 기반)
        # 브라우저에서 로그인 상태라면 자동 인증됨
        "rest_framework.authentication.SessionAuthentication",
        # Basic 인증 (아이디/비밀번호를 헤더로 보내는 방식)
        # 주로 테스트용으로 사용됨 (Postman, curl 등)
        "rest_framework.authentication.BasicAuthentication",
    ],
    # 기본 권한 설정
    # 인증된 사용자만 API 접근 가능
    "DEFAULT_PERMISSION_CLASSES": [
        # 로그인한 사용자만 API 사용 가능
        "rest_framework.permissions.IsAuthenticated",
    ],
    # 기본 페이지네이션 클래스 설정
    # API 목록 조회 시 페이지 단위로 데이터를 반환
    "DEFAULT_PAGINATION_CLASS": "todo.pagination.CustomPageNumberPagination",
    # 기본 페이지 크기
    # 한 페이지에 보여줄 데이터 개수
    "PAGE_SIZE": 3,
    # 응답 데이터 출력 형식(Renderer)
    "DEFAULT_RENDERER_CLASSES": [
        # JSON 형식 응답 (프론트엔드 / API 사용 시 기본)
        "rest_framework.renderers.JSONRenderer",
        # DRF 브라우저 API 화면 제공 (개발/테스트용)
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
